--!strict
local DailyRewardConfig = {
	{ day = 1, rewardType = "Currency", rewardAmount = 100 },
	{ day = 2, rewardType = "Currency", rewardAmount = 250 },
	{ day = 3, rewardType = "Currency", rewardAmount = 500 },
	{ day = 4, rewardType = "Currency", rewardAmount = 1000 },
	{ day = 5, rewardType = "Currency", rewardAmount = 2500 },
	{ day = 6, rewardType = "Currency", rewardAmount = 5000 },
	{ day = 7, rewardType = "Currency", rewardAmount = 25000 },
}

return DailyRewardConfig
